# Generated by Django 6.0.1 on 2026-01-21 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stud2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snm', models.CharField(max_length=50)),
                ('semail', models.EmailField(max_length=254)),
            ],
        ),
    ]
