# Generated by Django 6.0.1 on 2026-01-22 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_stud2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insertstud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.IntegerField()),
                ('name', models.CharField(max_length=40)),
                ('fees', models.IntegerField()),
            ],
        ),
    ]
